### ISSUE TITLE
Unexpected string parsing result

### ISSUE THREAD

**Issue by olegrok** [tarantool/icu-date#27]
```
icu_date = require('icu-date')
dt = icu_date.new()
p = icu_date.formats.pattern('yyyyMMdd')

dt:parse(p, '2021')
-- nil	Invalid status: "U_PARSE_ERROR". Result: "nil"	0 (OK)

tarantool> dt:parse(p, '2021-')
-- No error (strange)
tarantool> dt
---
- 0002-02-01T00:00:00.000Z -- Looks weird (in fact 2021 is parsed as 0002 02 01 for unknown (for me) reason)
...
```

I don't know how we should fix this error properly. Single option that I see is to check `position` argument of udat_parseCalendar and return an error in case if `position` < #date_string.

**Comment by olegrok** [comment]
Seems issue was fixed https://github.com/unicode-org/icu/pull/2006

**Comment by Totktonada** [comment]
NB: Fixed in libicu 71 (it is the release candidate) and following releases (71.1, ...).
